### PR TITLE
PL language file update and hiding chat box from guests

### PR DESCRIPTION
**Pull request by sq6jny**
Hello,
PL language file update will enable notification about new post, update in post, etc. for polish language
The chat_body.html modification will prevent from showing chat box to guests (maybe it is good to consider adding a new option for this?)

Best regards,
Marcin

### CODE REVIEW

**Comment by LMOspaceace** [comment]
showing the chat for guests is already part of the permission system for this extension. select the guest group and set them to not view chat.

**Comment by sq6jny** [comment]
Ok, now I have found that, thanks :)

2015-06-28 21:53 GMT+02:00 Darin Wilton notifications@github.com:

> showing the chat for guests is already part of the permission system for
> this extension. select the guest group and set them to not view chat.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LMOspaceace/ajaxchat/pull/44#issuecomment-116321239.

## 

Marcin Sroczyk
SQ6JNY

**Comment by LMOspaceace** [comment]
i have corrected the missing links in the language file and committed the change but did not change the template file. so the corrected pl/ajax_chat.php file is on my Git now. but there are several missing translations if you could have a look please

**Comment by sq6jny** [comment]
Ok, great, thank you

2015-06-29 0:19 GMT+02:00 Darin Wilton notifications@github.com:

> i have corrected the missing links in the language file and committed the
> change but did not change the template file. so the corrected
> pl/ajax_chat.php file is on my Git now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LMOspaceace/ajaxchat/pull/44#issuecomment-116355266.

## 

Marcin Sroczyk
SQ6JNY

**Pull request closed without merging**
