### PR TITLE
Clean code, fix bugs, add error handling, add russian translation

### PR DESCRIPTION
**Pull request by Tatiana5**
Clean code
Fix bugs (with permissions, shash at the end of the link, and other)
Add error handling
Add russian translation
And other changes

### CODE REVIEW

**Comment by Reaper88** [comment]
just curious as to the reason for adding the shash in the link?

**Comment by Tatiana5** [comment]
@Reaper88 
When typing the address manually, the browser itself substitutes a slash at the end of the link. This resulted in an error "No route found"

**Comment by Reaper88** [comment]
Which one? for future reference!

**Comment by Tatiana5** [comment]
Firefox (especially if one time to type a slash manually)

**Comment by Reaper88** [comment]
Then to just add the slash at the end of path in the routing.yml rectifies that error. Symfony's router puts it automatically, the last version of the 3.2 branch does it at least of that I'm sure please test, with your changes.

**Comment by Tatiana5** [comment]
If just add a slash, the links will stop working without a slash

**Comment by Reaper88** [comment]
So the router doesnt add them automaticly when just put in the path setting of the route?

**Comment by Tatiana5** [comment]
path: /chat
example.com/chat - work
example.com/chat/ - don't work

path: /chat/
example.com/chat - don't work
example.com/chat/ - work

Nothing is automatically added from the Symphony

**Comment by Reaper88** [comment]
Ok thanks for verifying

**Comment by Galixte** [comment]
@LMOspaceace

**Pull request merged**
