### PR TITLE
Fix sql queries

### PR DESCRIPTION
**Pull request by ghost**
Fix sql queries, test them yourself first before merging.
Don't know if it solves the issue.

### CODE REVIEW

**Comment by Reaper88** [comment]
What is the error you are getting for this request?

**Comment by ghost** [comment]
https://www.phpbb.com/community/viewtopic.php?f=456&t=2286221&start=825#p14280821
As per this erorr, trying to clean up sql code a bit for you ;)

**Comment by Reaper88** [comment]
This error doesn't mean to clean up SQL but that a syntax error as occured which in this case is a missing variable.

**Comment by ghost** [comment]
I know.. I already mentioned I don't know if it fixes the error, just came across the file and thought I would help spaceace with the code. The way I wrote the sql is along the phpBB Coding Guidelines.

**Comment by LMOspaceace** [comment]
the above does work. however, it is deleting 1 more than the set amount. the original leaves the correct amount and i cannot get any type of error from it

**Comment by ghost** [comment]
I think the code is rather odd.. You want to delete everything from the CHAT_TABLE with a message_id below the offset (offset is: config['prune_keep_ajax_chat'). So in the first SQL you select that message. Then you take that message id and you substract the offset again..
And all messages_id below the OFFSETx2 are deleted. So if the config-offset is set at 10, it will keep 20 messages_id's in the chat table.. ?

**Comment by Reaper88** [comment]
it can be confusing as the author of that part of the code i'll fix it tomorrow.

**Comment by Reaper88** [comment]
I've added the patch see https://github.com/LMOspaceace/ajaxchat/pull/57 for file changes

**Pull request closed without merging**
